[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  branch = "live-fix"

[context.deploy-preview]
  branch = "live-fix"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
